Fried-Chicken-Calculator/Controllers/UserHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fried_Chicken_Calculator.Models;

namespace Fried_Chicken_Calculator.Controllers
{
    public class UserHistoriesController : Controller
    {
        private CalculatorDBContext db = new CalculatorDBContext();

        // GET: UserHistories
        public ActionResult Index()
        {
            return View(db.UserHistories.ToList());
        }

        // GET: UserHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserHistory userHistory = db.UserHistories.Find(id);
            if (userHistory == null)
            {
                return HttpNotFound();
            }
            return View(userHistory);
        }

        // GET: UserHistories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserHistories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserNumber,History")] UserHistory userHistory)
        {
            if (ModelState.IsValid)
            {
                db.UserHistories.Add(userHistory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userHistory);
        }

        // GET: UserHistories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserHistory userHistory = db.UserHistories.Find(id);
            if (userHistory == null)
            {
                return HttpNotFound();
            }
            return View(userHistory);
        }

        // POST: UserHistories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserNumber,History")] UserHistory userHistory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userHistory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userHistory);
        }

        // GET: UserHistories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserHistory userHistory = db.UserHistories.Find(id);
            if (userHistory == null)
            {
                return HttpNotFound();
            }
            return View(userHistory);
        }

        // POST: UserHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserHistory userHistory = db.UserHistories.Find(id);
            db.UserHistories.Remove(userHistory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fried-Chicken-Calculator/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fried_Chicken_Calculator.Models;

namespace Fried_Chicken_Calculator.Controllers
{
    public class UsersController : Controller
    {
        private CalculatorDBContext db = new CalculatorDBContext();

        // GET: Users
        public ActionResult Index()
        {
            var context = new CalculatorDBContext();
            //var contextuser = from a in db.Users
            //                  join b in db.UserHistories on a.UserNumber equals b.UserNumber
            //                  select new {
            //                      a.UserName,
            //                      a.UserNumber,
            //                      a.UserPassword,
            //                      b.History,
            //                      a.UserMoney
            //                  };
            var contextuser = context.Users.ToList();
            return View(contextuser);
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,UserName,UserPassword,UserNumber,UserMoney")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,UserName,UserPassword,UserNumber,UserMoney")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fried-Chicken-Calculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("炒鸡计算器", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li id="Iuserinfo" style="display:none">@Html.ActionLink("后台用户信息", "Index", "Users")</li>
                    <li id="Iuserrecode" style="display:none">@Html.ActionLink("后台历史记录", "index", "UserHistories")</li>
                    <li id="loginstate" >@Html.ActionLink("登录", "Login", "Home")</li>
                    <li id="loginOut" style="display:none">@Html.ActionLink("注销", "LoginOut", "Home")</li>
                    <li id="register">@Html.ActionLink("注册", "Register", "Home")</li>
                    @*<li>@Html.Label("Isession",Session["user"])</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 炒鸡计算器</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script type="text/javascript">
    $(function () {
        $.ajax({
            type: "GET",
            url: "/Home/GetSession",
            async: true,
            dataType: "text",
            success: function (result) {
                //console.log(result);
                //alert(result);
                if (result != "") {
                 $("#loginstate").css('display', 'none');
                    $("#loginOut").css('display', 'block');
                    $("#register").css('display', 'none');
                    if (result == "admin") {
                        $("#Iuserinfo").css('display', 'block');
                        $("#Iuserrecode").css('display', 'block');
                    }
                        
                 } else {
                 $("#loginstate").css('display', 'block');
                    $("#loginOut").css('display', 'none');
                    $("#register").css('display', 'block');
                }
                
            }
        });
    });
</script>